server:
  port: 8886
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: cn.zhangjingyao.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#pageHaleper 配置
pagehelper:
  #pageNum<=0 会查询第一页，如果 pageNum>总页数 会查询最后一页
  reasonable: true
spring:
  datasource:
    druid:
    #配置监控
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        #IP白名单
        allow: 127.0.0.1
        #IP黑名单
        deny:
      #driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://192.168.0.102:3306/zjyffd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.201:3306/zjyffd?useSSL=FALSE&serverTimezone=UTC
      username: root
      password: root
      #下面为连接池的补充设置，应用到上面所有数据源中
      #初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #配置获取连接等待超时的时间
    　max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    　time-between-connect-error-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
    　min-evictable-idle-time-millis: 30000
    　validation-query: select 'x'
    　test-while-idle:  true
    　test-on-borrow:  false
    　test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
    　pool-prepared-statements:  true
    　max-pool-prepared-statement-per-connection-size:  20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    　filters: stat
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    　connect-properties:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    static-path-pattern: /static/**
  activiti:
    database-schema-update: true
  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5


